---
title: "Useful Data Science Resources"
output:
    github_document:
    #html_document:
    #  theme: tactile
    #  highlight: textmate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	warning = TRUE,
	comment = "##",
	prompt = TRUE,
	tidy = TRUE,
	tidy.opts = list(width.cutoff = 75)
)
```
|                                                   |                                                             |
|:------------------------------------------------- |:------------------------------------------------------------|
| [**Software Tools**](#software-tools)             | [**Books**](#books)                                         |
| - [Programming Languages](#programming-languages) | - [R and Basic Statistics](#r-and-basic-statistics)         |
| - [Text Editors](#text-editors)                   | - [R Programming](#r-programming)                           |
| - [Markdown Editors](#markdown-editors)           | - [R Reference](#r-reference)                               |
| - [IDEs](#ides)                                   | - [R Graphics](#r-graphics)                                 |
| - [Version Control Tools](#version-control)       | - [Data Science and Visualization](#data-science)           |
| [**Web Resources**](#web-resources)               | - [Spatial Analysis](#spatial-analysis)                     |
|                                                   | - [Mixed Effects Modeling](#mixed-effects-modeling)         |
|                                                   | - [Web Scraping and Text Mining](#web-scraping)             |
|                                                   | - [Statistics and Programming in Python](#stats-and-python) |

## <a name="software-tools"></a>Software Tools

### <a name="programming-languages"></a>Programming Languages
- [R](https://cran.r-project.org/) (MacOS, Windows, Linux)
- [Python](https://www.python.org/) (MacOS, Windows, Linux)

### <a name="text-editors"></a>Text Editors
- [Atom](https://atom.io/) (MacOS, Windows)
- [TextWrangler](http://www.barebones.com/products/textwrangler/download.html) (MacOS)
- [nvAlt](http://brettterpstra.com/projects/nvalt/) (MacOS)
- [Notepad++](https://notepad-plus-plus.org/) (Windows)

### <a name="markdown-editors"></a>Markdown Editors
- [MacDown](http://macdown.uranusjr.com/) (MacOS)
- [MarkdownPad2](http://markdownpad.com/) (Windows)

### <a name="ides"></a>IDEs
- [RStudio](https://www.rstudio.com/) for **R** (current version is 0.99.903) (MacOS, Windows)
- [y-hat Rodeo](https://www.yhat.com/products/rodeo) for **Python** (current version is 2.0.13) (MacOS, Windows, Linux)

### <a name="version-control"></a>Version Control Tools
- [GitHub](https://github.com/) (Website)
- [GitHub Desktop](https://desktop.github.com/) (MacOS, Windows)

## <a name="web-resources"></a>Web Resources
- [CRAN (Comprehensive R Archive Network)](https://cran.r-project.org/)
- [DataCamp](https://www.datacamp.com)
- [Software Carpentry](http://software-carpentry.org/)
- [Data Carpentry](http://www.datacarpentry.org/)
- [rOpenSci](https://ropensci.org/)
- [Stack Overflow](http://stackoverflow.com/)
- [Online R Exercises](http://r-exercises.com/start-here-to-learn-r/)
- [R-bloggers](https://www.r-bloggers.com/)

## <a name="books"></a>Books

### <a name="r-and-basic-statistics"></a>R and Basic Statistics
* Caffo, B. (2015). *Statistical Inference for Data Science.* Lean Publishing.
* Caffo, B. (2016). *Regression Models for Data Science in R.* Lean Publishing.
* Dalgaard, P. (2008). *Introductory Statistics with R* (Second Edition). New York: Springer.
* Shahbaba, B. (2012). *Biostatistics with R.* New York: Springer.

### <a name="r-programming"></a>R Programming
* Adler, J. (2009). *R in a Nutshell.* Sebastopol, CA: O’Reilly Media.
* Kabacoff, R. I. (2011). *R in Action: Data Analysis and Graphics with R.* Shelter Island, NY: Manning Publications Co.
* Matloff, N. (2011). *The Art of R Programming: A tour of Statistical Software Design.* San Francisco: No Starch Press.
* Peng, R. (2016). *R Programming for Data Science.* Lean Publishing.
* Peng, R. (2016). *Exploratory Data Analysis with R.* Lean Publishing.
* Zuur, A. F., Ieno, E. N., & Meesters, E. H. W. G. (2009). *A Beginner’s Guide to R.* New York: Springer.

### <a name="r-reference"></a>R Reference
* Crawley, M. J. (2012). *The R Book* (Second Edition). Chichester, UK: John Wiley & Sons Ltd.
* Gardener, M. (2012). *The Essential R Reference.* Indianapolis, IN: John Wiley & Sons, Inc.
* Teetor, P. (2011). *R Cookbook.* Sebastopol, CA: O’Reilly Media.

### <a name="r-graphics"></a>R Graphics
* Chang, W. (2013). *R Graphics Cookbook.* Sebastopol, CA: O’Reilly Media.
* Wickham, H. (2016). *ggplot2: Elegant Graphics for Data Analysis* (Second Edition.). Springer International Publishing.

### <a name="data-science"></a>Data Science and Visualization
* Dale, K. (2016). *Data Visualization with Python and JavaScript.* Sebastopol, CA: O’Reilly Media.
* Grus, J. (2015). *Data Science from Scratch.* Sebastopol, CA: O’Reilly.
* Irizarry, R. A., & Love, M. I. (2015). *Data Analysis for the Life Sciences.* Lean Publishing.
* Kazil, J., & Jarmul, K. (2016). *Data Wrangling with Python.* Sebastopol, CA: O’Reilly.
* Peng, R. D., & Matsui, E. (2015). *The Art of Data Science.* Lean Publishing.
* Zumel, N., & Mount, J. (2014). *Practical Data Science with R.* Shelter Island, NY: Manning Publications Co.

### <a name="spatial-analysis"></a>Spatial Analysis
* Bivand, R. S., Pebesma, E. J., & Gómez-Rubio, V. (2008). *Applied Spatial Data Analysis with R.* New York: Springer.

### <a name="mixed-effects-modeling"></a>Mixed Effects Models
* Zuur, A. F., Ieno, E. N., Walker, N. J., Savaliev, A. A., & Smith, G. M. (2009). *Mixed Effects Models and Extensions in Ecology with R.* New York: Springer.

### <a name="web-scraping"></a>Web Scraping and Text Mining
* Friedl, J. E. F. (2000). *Mastering Regular Expressions* (Third Edition). Sebastopol, CA: O’Reilly Media.
* Mitchell, R. (2015). *Web Scraping with Python.* Sebastopol, CA: O’Reilly Media.
* Nolan, D., & Temple Lang, D. (2014). *XML and Web Technologies for Data Sciences with R.* New York: Springer.

### <a name="stats-and-python"></a>Statistics and Programming in Python
* Downey, A. (2014). *Think Stats* (Second Edition). Sebastopol, CA: O’Reilly Media.
* Lubanovic, B. (2014). *Introducing Python.* Sebastopol, CA: O’Reilly Media.
* McKinney, W. (2013). *Python for Data Analysis.* Sebastopol, CA: O’Reilly.
